"""MkDocs hook: keep every link in doc/*.md working on the site.

doc/*.md links to files elsewhere in the repository — `../README.md`,
`../examples/foo.py`, `../benchmarks/reproducers/README.md`. Inside the docs
site those paths escape the docs directory and 404. This rewrites any relative
link that resolves outside doc/ to the file's GitHub URL, and leaves links
inside doc/ for mkdocs to validate. Pages generated by website/gen_pages.py
are already rewritten there and are skipped here.

It also applies publication/doc_allowlist.txt, so a site built in the private
tree shows the same doc/ files the public export ships. In the export tree
the list is absent and doc/ already holds only the allowlisted files.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "doc"
BLOB = "https://github.com/pavelhorak/pion/blob/main/"
ALLOWLIST = ROOT / "publication" / "doc_allowlist.txt"
_LINK = re.compile(r"(!?\[[^\]]*\]\()([^)\s]+)((?:\s+\"[^\"]*\")?\))")


def _allowed_docs() -> set[str] | None:
    if not ALLOWLIST.exists():
        return None
    out = set()
    for line in ALLOWLIST.read_text(encoding="utf-8").splitlines():
        entry = line.split("#", 1)[0].strip()
        if entry:
            out.add(entry)
    return out


def on_files(files, config):
    allowed = _allowed_docs()
    if allowed is None:
        return files
    for f in list(files.documentation_pages()):
        if getattr(f, "generated_by", None):
            continue                   # assembled by gen_pages.py
        if f.src_uri not in allowed:
            files.remove(f)
    return files


def on_page_markdown(markdown: str, page, config, files) -> str:
    if getattr(page.file, "generated_by", None):
        return markdown
    src_dir = (DOC / page.file.src_uri).parent

    def fix(m):
        target = m.group(2)
        if re.match(r"^(https?:|mailto:|#|/)", target):
            return m.group(0)
        path, _, frag = target.partition("#")
        if not path:
            return m.group(0)
        p = (src_dir / path).resolve()
        try:
            p.relative_to(DOC)
            return m.group(0)          # inside doc/: mkdocs handles it
        except ValueError:
            pass
        try:
            rel = p.relative_to(ROOT).as_posix()
        except ValueError:
            return m.group(0)
        new = BLOB + rel + ("#" + frag if frag else "")
        return m.group(1) + new + m.group(3)

    return _LINK.sub(fix, markdown)
